### ISSUE TITLE
AVSを実装する

### ISSUE THREAD

**Issue by SaKu2110** [p2hacks/team1901#4]
参考資料
https://dev.classmethod.jp/smartphone/amazon-alexa-voice-service/
https://qiita.com/moritalous/items/a3e847612dd2bf4fed99

**Comment by YukiKoshi** [comment]
https://developer.amazon.com/ja/docs/alexa-voice-service/authorize-on-product.html

**Comment by YukiKoshi** [comment]
https://github.com/alexa/avs-device-sdk/wiki/How-to-cross-compile-the-AVS-Device-SDK-for-iOS

**Comment by YukiKoshi** [comment]
https://books.google.co.jp/books?id=Q2NqDwAAQBAJ&pg=PT254&lpg=PT254&dq=AVS%E3%80%80iOS%E5%AE%9F%E8%A3%85&source=bl&ots=vDJnfEhYio&sig=ACfU3U3kaqtz9dxjpEPVtmYlTOHUZidb-A&hl=ja&sa=X&ved=2ahUKEwiXppCzwb7gAhUBfrwKHf_tARoQ6AEwBXoECAoQAQ#v=onepage&q=AVS%E3%80%80iOS%E5%AE%9F%E8%A3%85&f=false

プレビューのため、すべて読むことはできないが、参考文献として提示

**Comment by YukiKoshi** [comment]
Alexaスキル制作テクニック : 音声認識自然言語理解機械学習 : skill:アレクサ用アプリ
https://lib-auth.fun.ac.jp/webopac/BB00246272

未来大にあるAlexaの参考文献
